chore: non-semver chars

diff --git a/.github/actions/parse-semver/action.yml b/.github/actions/parse-semver/action.yml
--- a/.github/actions/parse-semver/action.yml
+++ b/.github/actions/parse-semver/action.yml
@@ -35,6 +35,14 @@ runs:
         VERSION="${FULL_VERSION#v}"
 
         # Filter out non-semver characters
+        CLEAN_VERSION=$(echo "$VERSION" | sed -E 's/[^0-9a-zA-Z.-]+//g')
+
+        if [[ "$CLEAN_VERSION" != "$VERSION" ]]; then
+            echo "Semver version includes invalid characters. Exiting..."
+            exit 1
+        fi
+
+        # Filter out non-semver characters
         VERSION=$(echo "$VERSION" | sed -E 's/[^0-9a-zA-Z.-]+//g')
 
         # Split version into parts
