second step on optional

diff --git a/.github/workflows/needing-an-optional-job-alternate.yml b/.github/workflows/needing-an-optional-job-alternate.yml
--- a/.github/workflows/needing-an-optional-job-alternate.yml
+++ b/.github/workflows/needing-an-optional-job-alternate.yml
@@ -18,14 +18,24 @@ jobs:
 
   optional-job:
     needs: [first-job]
+    continue-on-error: true
     runs-on: ubuntu-latest
     if: inputs.run-optional
     steps:
-      - run: |
+      - id: run-optional-step
+        run: |
           echo "Running optional step"
           if [[ ${{ inputs.fail-optional }} == "true" ]]; then
             echo "Optional step failed!"
             exit 1
+          fi
+      - id: validate-optional-step
+        run: |
+          RESULT=${{ step.run-optional-step.result }}
+          if [[ "$RESULT" != 'success' && "$RESULT" != 'skipped' ]]; then
+            exit 1
+          else
+            echo "Optional job was successful or was skipped, proceeding."
           fi
 
   # This is an alternate approach for "needing" an optional job.
@@ -33,36 +43,36 @@ jobs:
   #   if: always() && (needs.optional-job.result == 'success' || needs.optional-job.result == 'skipped')
   # we perform the validation here and future jobs only need to add this job their `needs` array
   # NOTE: Following jobs will also need `if: success()` or they will be skipped. See: https://github.com/actions/runner/issues/2205
-  proceed:
-    runs-on: ubuntu-latest
-    outputs:
-      proceed: ${{ steps.proceed.outputs.proceed }}
-    needs: [optional-job]
-    if: always()
-    steps:
-      - name: Check for failure
-        id: proceed
-        run: |
-          RESULT=${{ needs.optional-job.result }}
-          if [[ "$RESULT" != 'success' && "$RESULT" != 'skipped' ]]; then
-            exit 1
-          else
-            echo "Optional job was successful or was skipped, proceeding."
-            echo "proceed=true" >> "$GITHUB_OUTPUT"
-          fi
+  # proceed:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     proceed: ${{ steps.proceed.outputs.proceed }}
+  #   needs: [optional-job]
+  #   if: always()
+  #   steps:
+  #     - name: Check for failure
+  #       id: proceed
+  #       run: |
+  #         RESULT=${{ needs.optional-job.result }}
+  #         if [[ "$RESULT" != 'success' && "$RESULT" != 'skipped' ]]; then
+  #           exit 1
+  #         else
+  #           echo "Optional job was successful or was skipped, proceeding."
+  #           echo "proceed=true" >> "$GITHUB_OUTPUT"
+  #         fi
 
   # We want this job to run if `optional-job` was successful or skipped
   # We _do not_ want this job if `optional-job` failed
   depends-on-optional:
-    needs: [proceed]
-    if: ${{ needs.proceed.outputs.proceed }}
+    needs: [optional-job]
+    # if: ${{ needs.proceed.outputs.proceed }}
     runs-on: ubuntu-latest
     steps:
       - run: echo "Optional job passed or was skipped!"
 
   also-depends-on-optional:
-    needs: [proceed]
-    if: ${{ needs.proceed.outputs.proceed }}
+    needs: [optional-job]
+    # if: ${{ needs.proceed.outputs.proceed }}
     runs-on: ubuntu-latest
     steps:
       - run: echo "Optional job passed or was skipped!"
