shove

diff --git a/.github/workflows/use-needs-to-skip-all-following-steps.yml b/.github/workflows/use-needs-to-skip-all-following-steps.yml
--- a/.github/workflows/use-needs-to-skip-all-following-steps.yml
+++ b/.github/workflows/use-needs-to-skip-all-following-steps.yml
@@ -23,23 +23,18 @@ jobs:
           set +e
           CTC_RESULT=$(sfchangecase create --location git://github.com/salesforcecli/testPackageRelease.git --release salesforcecli/testPackageRelease.$(date +%F) --json)
           set -e
-          echo "before echo"
-          echo $CTC_RESULT
-          echo "after echo"
 
-          # STATUS=$(printf '%s' "$CTC_RESULT" | jq -r '.status')
-          # CTC_ID=$(printf '%s' "$CTC_RESULT" | jq -r '.result.id')
+          STATUS=$(printf '%s' "$CTC_RESULT" | jq -r '.status')
+          CTC_ID=$(printf '%s' "$CTC_RESULT" | jq -r '.result.id')
 
-          # if [[ "$STATUS" == "0" && "$CTC_ID" != "null" ]]; then
-          #     echo "Successfully created case with ID: $CTC_ID"
-          #     echo "ctcId=$CTC_ID" >> "$GITHUB_OUTPUT"
-          # else
-          #     echo "CTC failed to open a case. Result:"
-          #     echo "$CTC_RESULT"
-          #     exit 1
-          # fi
-          echo "attempting to exit with exitcode 1"
-          # exit 1
+          if [[ "$STATUS" == "0" && "$CTC_ID" != "null" ]]; then
+              echo "Successfully created case with ID: $CTC_ID"
+              echo "ctcId=$CTC_ID" >> "$GITHUB_OUTPUT"
+          else
+              echo "CTC failed to open a case. Result:"
+              echo "$CTC_RESULT"
+              exit 1
+          fi
 
   final-log:
     needs: [exit-early]
